version: '3.9'

services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./db_data:/var/lib/mysql

# docker-compose up -d
